Find PR branch

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -4,6 +4,9 @@ pipeline {
         timeout(time: 60, unit: 'MINUTES')
     }
     agent { label 'cicd' }
+    environment {
+        GITHUB_CREDS = credentials('jenkins-checkouts')
+    }
     stages {
         stage('Checkout') {
             steps {
@@ -23,11 +26,18 @@ pipeline {
         stage('Match edge-cloud branch') {
             steps {
                 dir(path: 'go/src/github.com/mobiledgex/edge-cloud-infra') {
-                    sh label: 'make edge-cloud-version-set', script: '''$!/bin/bash
+                    sh label: 'make edge-cloud-version-set', script: '''#!/bin/bash
 export PATH=$PATH:/usr/local/go/bin:$WORKSPACE/go/bin:$HOME/go/bin
 export GOPATH=$WORKSPACE/go
 
-INFRA_BRANCH=$( git rev-parse --abbrev-ref HEAD )
+PR=$( git rev-parse --abbrev-ref HEAD | cut -d- -f2 )
+INFRA_BRANCH=$( curl -u "$GITHUB_CREDS_USR:GITHUB_CREDS_PSW" "https://api.github.com/repos/mobiledgex/edge-cloud-infra/pulls/${PR}" \
+                | jq -r '.head.ref // empty' )
+if [[ -z "$INFRA_BRANCH" ]]; then
+    echo "Failed to determine PR branch" >&2
+    exit 2
+fi
+echo "Infra branch: $INFRA_BRANCH"
 
 EC_BRANCH=$( git -C ../edge-cloud branch -a | awk -v "BR=remotes/origin/${INFRA_BRANCH}" '$NF == BR' )
 if [[ -n "$EC_BRANCH" ]]; then
