CI/CD fixes - Run unit tests for each PR (#1095)
E2E tests are still not working on Linux.

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -1,8 +1,12 @@
 pipeline {
     options {
+        skipDefaultCheckout true
         timeout(time: 60, unit: 'MINUTES')
     }
-    agent any
+    agent { label 'cicd' }
+    environment {
+        GITHUB_CREDS = credentials('jenkins-checkouts')
+    }
     stages {
         stage('Checkout') {
             steps {
@@ -10,29 +14,56 @@ pipeline {
                     checkout scm
                 }
                 dir(path: 'go/src/github.com/mobiledgex/edge-cloud') {
-                    git url: 'git@github.com:mobiledgex/edge-cloud.git'
+                    git credentialsId: 'jenkins-checkouts',
+                        url: 'https://github.com/mobiledgex/edge-cloud.git'
                 }
                 dir(path: 'go/src/github.com/mobiledgex/edge-proto') {
-                    git url: 'git@github.com:mobiledgex/edge-proto.git'
+                    git credentialsId: 'jenkins-checkouts',
+                        url: 'https://github.com/mobiledgex/edge-proto.git'
                 }
             }
         }
-        stage('Edge-Cloud Version') {
+        stage('Match branches') {
             steps {
                 dir(path: 'go/src/github.com/mobiledgex/edge-cloud-infra') {
-                    sh label: 'make edge-cloud-version-set', script: '''$!/bin/bash
-export PATH=$PATH:$WORKSPACE/go/bin:$HOME/go/bin
+                    sh label: 'make edge-cloud-version-set', script: '''#!/bin/bash
+export PATH=$PATH:/usr/local/go/bin:$WORKSPACE/go/bin:$HOME/go/bin
 export GOPATH=$WORKSPACE/go
-make edge-cloud-version-set
+
+PR=$( git rev-parse --abbrev-ref HEAD | cut -d- -f2 )
+PR_URL="https://api.github.com/repos/mobiledgex/edge-cloud-infra/pulls/${PR}"
+INFRA_BRANCH=$( curl -sf -u "$GITHUB_CREDS_USR:$GITHUB_CREDS_PSW" "$PR_URL" \
+                | jq -r '.head.ref // empty' )
+if [[ -z "$INFRA_BRANCH" ]]; then
+    echo "Failed to determine PR branch" >&2
+    exit 2
+fi
+echo "Infra branch: $INFRA_BRANCH"
+
+EC_BRANCH=$( git -C ../edge-cloud branch -a | awk -v "BR=remotes/origin/${INFRA_BRANCH}" '$NF == BR' )
+if [[ -n "$EC_BRANCH" ]]; then
+    echo "Checking out matching edge-cloud branch: ${INFRA_BRANCH}"
+    git -C ../edge-cloud checkout origin/${INFRA_BRANCH} || exit 2
+else
+    echo "Building with edge-cloud master branch"
+fi
+
+PROTO_BRANCH=$( git -C ../edge-proto branch -a | awk -v "BR=remotes/origin/${INFRA_BRANCH}" '$NF == BR' )
+if [[ -n "$PROTO_BRANCH" ]]; then
+    echo "Checking out matching edge-proto branch: ${INFRA_BRANCH}"
+    git -C ../edge-proto checkout origin/${INFRA_BRANCH} || exit 2
+else
+    echo "Building with edge-proto master branch"
+fi
                     '''
                 }
             }
         }
-        stage('Build') {
+        stage('Clean') {
             steps {
                 dir(path: 'go/src/github.com/mobiledgex/edge-cloud') {
                     sh label: 'make clean', script: '''#!/bin/bash
-export PATH=$PATH:$WORKSPACE/go/bin:$HOME/go/bin
+export PATH=$PATH:/usr/local/go/bin:$WORKSPACE/go/bin:$HOME/go/bin
 export GOPATH=$WORKSPACE/go
 make clean
                     '''
@@ -43,9 +74,21 @@ make clean
                 dir(path: 'go/src/github.com/mobiledgex/edge-cloud-infra') {
                     sh label: 'git clean edge-cloud-infra', script: 'git clean -f -d -x'
                 }
+            }
+        }
+        stage('GRPC checkout') {
+            when { not { expression { fileExists 'go/src/github.com/grpc-ecosystem/grpc-gateway' } } }
+            steps {
+                dir(path: 'go/src/github.com/grpc-ecosystem') {
+                    sh label: 'git clone grpc-gateway', script: 'git clone https://github.com/mobiledgex/grpc-gateway.git'
+                }
+            }
+        }
+        stage('Build') {
+            steps {
                 dir(path: 'go/src/github.com/mobiledgex/edge-cloud') {
                     sh label: 'go mod download', script: '''#!/bin/bash
-export PATH=$PATH:$WORKSPACE/go/bin:$HOME/go/bin
+export PATH=$PATH:/usr/local/go/bin:$WORKSPACE/go/bin:$HOME/go/bin
 export GOPATH=$WORKSPACE/go
 export GO111MODULE=on
 go mod download
@@ -53,14 +96,14 @@ go mod download
                 }
                 dir(path: 'go/src/github.com/mobiledgex/edge-cloud') {
                     sh label: 'make tools', script: '''#!/bin/bash
-export PATH=$PATH:$WORKSPACE/go/bin:$HOME/go/bin
+export PATH=$PATH:/usr/local/go/bin:$WORKSPACE/go/bin:$HOME/go/bin
 export GOPATH=$WORKSPACE/go
 make tools
                     '''
                 }
                 dir(path: 'go/src/github.com/mobiledgex/edge-cloud-infra') {
                     sh label: 'make', script: '''#!/bin/bash
-export PATH=$PATH:$WORKSPACE/go/bin:$HOME/go/bin
+export PATH=$PATH:/usr/local/go/bin:$WORKSPACE/go/bin:$HOME/go/bin
 export GOPATH=$WORKSPACE/go
 make
                     '''
@@ -69,31 +112,19 @@ make
         }
         stage('Test') {
             options {
+                lock('testbed')
                 timeout(time: 40, unit: 'MINUTES')
             }
             steps {
-                lock('testbed') {
-                    retry(2) {
-                        sleep 10
-                        dir(path: 'go/src/github.com/mobiledgex/edge-cloud-infra') {
-                            sh label: 'unit tests', script: '''#!/bin/bash
-export PATH=$PATH:$WORKSPACE/go/bin:$HOME/go/bin:/usr/lib/postgresql/11/bin
+                retry(2) {
+                    sleep 10
+                    dir(path: 'go/src/github.com/mobiledgex/edge-cloud-infra') {
+                        sh label: 'unit tests', script: '''#!/bin/bash
+export PATH=$PATH:/usr/local/go/bin:$WORKSPACE/go/bin:$HOME/go/bin:/usr/lib/postgresql/10/bin
 export GOPATH=$WORKSPACE/go
 export GO111MODULE=on
 UNIT_TEST_LOG=/tmp/edge-cloud-infra-unit-test.${BUILD_TAG}.log make unit-test
-                            '''
-                        }
-                    }
-                    sleep 60
-                    retry(2) {
-                        sleep 10
-                        dir(path: 'go/src/github.com/mobiledgex/edge-cloud-infra') {
-                            sh label: 'make test', script: '''#!/bin/bash
-export PATH=$PATH:$WORKSPACE/go/bin:$HOME/go/bin:/usr/lib/postgresql/11/bin
-export GOPATH=$WORKSPACE/go
-make test
-                            '''
-                        }
+                        '''
                     }
                 }
             }
